---
season_data:
  wild:
    zip_filename:      "Sofortmelder_Wildwachsende_Pflanze.zip"
    phases_filename:   "PH_Beschreibung_Phase.txt"
    stations_filename: "PH_Beschreibung_Phaenologie_Stationen.txt"
    plants_filename:   "PH_Beschreibung_Pflanze_Wildwachsende_Pflanze.txt"
    season_data_filenames:
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Beifuss_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Birke_alle_Arten__akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Erle_alle_Arten__akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Esche_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Forsythie_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Haenge-Birke_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Hasel_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Huflattich_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Loewenzahn_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Sal-Weide_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Schneegloeckchen_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Schwarzer_Holunder_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Sommer-Linde_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Stiel-Eiche_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Robinie_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Rosskastanie_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Rotbuche_akt.txt"
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Schneegloeckchen_akt.txt"
  culture:
    zip_filename:      "Sofortmelder_Landwirtschaft_Kulturpflanze.zip"
    phases_filename:   "PH_Beschreibung_Phase.txt"
    stations_filename: "PH_Beschreibung_Phaenologie_Stationen.txt"
    plants_filename:   "PH_Beschreibung_Pflanze_Landwirtschaft_Kulturpflanze.txt"
    season_data_filenames:
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Schneegloeckchen_akt.txt"
  fruits:
    zip_filename:      "Sofortmelder_Obst.zip"
    phases_filename:   "PH_Beschreibung_Phase.txt"
    stations_filename: "PH_Beschreibung_Phaenologie_Stationen.txt"
    plants_filename:   "PH_Beschreibung_Pflanze_Obst.txt"
    season_data_filenames:
      - "PH_Sofortmelder_Wildwachsende_Pflanze_Schneegloeckchen_akt.txt"

dates:
  column_names:
    - "Qualitaetsniveau"
    - "Stations_id"
    - "Referenzjahr"
    - "Objekt_id=Pflanze"
    - "Phase_id=Phase"
    - "Eintrittsdatum"
    - "Eintrittsdatum_QB"
    - "Jultag"


seasons:
  Vorfrühling:
    - name: "Hasel"
      phase: "Blüte Beginn"
    - name: "Schneeglöckchen"
      phase: "Blüte Beginn"
      type: "wild"
      file: "PH_Sofortmelder_Wildwachsende_Pflanze_Schneegloeckchen_akt.txt"
  Erstfrühling:
    - name: "Forsythie"
      phase: "Blüte Beginn"
      type:  "wild"
      file:  "PH_Sofortmelder_Wildwachsende_Pflanze_Forsythie.txt"
    - name: "Stachelbeere"
      phase: "Blattentfaltung Beginn"
      file:  "PH_Sofortmelder_Obst_Stachelbeere.txt"
  Vollfrühling:
    - name: "Apfel"
      phase: "Blüte Beginn"
      file:  "PH_Sofortmelder_Obst_Apfel.txt"
    - name: "Stiel-Eiche"
      phase: "Blattentfaltung Beginn"
      type:  "wild"
      file:  "PH_Sofortmelder_Wildwachsende_Pflanze_Stiel-Eiche_akt.txt"
  Frühsommer:
    - name: "Schwarzer Holunder"
      phase: "Blüte Beginn"
      type:  "wild"
      file:  "PH_Sofortmelder_Wildwachsende_Pflanze_Schwarzer_Holunder_akt.txt"
    - name: "Robinie"
      phase: "Blüte Beginn"
  Hochsommer:
    - name: "Sommer-Linde"
      phase: "Blüte Beginn"
      type:  "wild"
      file:  "PH_Sofortmelder_Wildwachsende_Pflanze_Sommer-Linde_akt.txt"
    - name: "Johannisbeere, alle Sorten"
      phase: "erste reife Früchte"
      file:  "PH_Sofortmelder_Obst_Johannisbeere_alle_Sorten.txt"
  Spätsommer:
    - name: "Apfel, frühe Reife"
      phase: "erste reife Früchte"
    - name: "Eberesche"
      phase: "erste reife Früchte"
      type:  "wild"
      file:  "PH_Sofortmelder_Wildwachsende_Pflanze_Esche_akt.txt"
  Frühherbst:
    - name: "Schwarzer Holunder"
      phase: "erste reife Früchte"
    - name: "Kornelkirsche"
      phase: "erste reife Früchte"
  Vollherbst:
    - name: "Rosskastanie"
      phase: "erste reife Früchte"
    - name: "Stiel-Eiche"
      phase: "erste reife Früchte"
  Spätherbst:
    - name: "Stiel-Eiche"
      phase: "herbstliche Blattverfärbung"
    - name: "Eberesche"
      phase: "herbstlicher Blattfall"
  Winter:
    - name: "Stiel-Eiche"
      phase: "herbstlicher Blattfall"
    - name: "Apfel, späte Reife"
      phase: "herbstlicher Blattfall"
    - name: "Europäische Lärche"
      phase: "herbstlicher Nadelfall"
